#-------------------------------
# General Site Settings
title: Zhaoming

menu:
#- {name: 'About', url: ''}
- {name: 'Publication', url: 'publications.html'}
#- {name: 'Software', url: 'software.html'}
#- {name: 'Projects', url: 'projects.html'}
- {name: 'Contact', url: 'contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Zhaoming Xie is a PhD student at University of British Columbia'
  rel-author: 'Zhaoming Xie'
  rel-publisher: 'Zhaoming Xie'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: 'UA-113566398-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# About Section

about: >
  ## About Me

  I am a PhD student at the University of British Columbia working with [Professor Michiel van de Panne](http://www.cs.ubc.ca/~van/). I am interested in making legged robot move using tools from control theory and machine learning.
  
    
  I completed my master at Georgia Tech, working with [Professor Karen Liu](https://www.cc.gatech.edu/~karenliu/Home.html).


#-------------------------------
# Research Section

publication: >
  ## Publication


#-------------------------------
# Work Section
  ## Prjotects


#-------------------------------
# Software Section

software: >
  ## Software


#-------------------------------
# Contact Section

contact: >
  ## Contact
  
  If you'd like to know more about my research or would just like to discuss past or future projects, feel free to contact me [by email](mailto:zxie47@cs.ubc.ca).


social:
- {icon: 'github', link: 'https://github.com/ZhaomingXie'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/zhaoming-xie-5285218b/'}
- {icon: 'envelope', link: 'zxie47@cs.ubc.ca'}
# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
